### ISSUE TITLE
[240612] BOJ 1004 어린 왕자 Silver3

### ISSUE THREAD

**Issue by InbumS** [Hwarang2Platinum/algorithm#178]
# <a href="https://www.acmicpc.net/problem/1004" target="_blank">백준링크</a>

## Solver
- [x] 김인엽 @wintiger98 
- [ ] 김경호 @kkho9654 
- [x] 송인범 @InbumS 
- [x] 오화랑 @Hwarang-Oh 
- [ ] 이찬민 @chanmin97 
- [ ] 조승기 @seungki-cho
- [x] 김종호 @dino9881

기하 연습 문제, 기하가 나올수도 있다는 무서운 사실을 아시나요?

**Comment by Hwarang-Oh** [comment]
뭔가 진짜 방심하다가 나올것 같은 유형같긴 하네여 ㅋㅋㅋㅋㅋ
