### ISSUE TITLE
[240219] BOJ 16236 아기상어 G3

### ISSUE THREAD

**Issue by seungki-cho** [Hwarang2Platinum/algorithm#2]
# [백준링크](https://www.acmicpc.net/problem/16236)

## Solver
- [x] 김인엽 @wintiger98 
- [x] 김경호 @kkho9654 
- [x] 송인범 @InbumS 
- [ ] 오화랑 @Hwarang-Oh 
- [x] 이찬민 @chanmin97 
- [x] 조승기 @seungki-cho

**Comment by kkho9654** [comment]
asd
