### ISSUE TITLE
[240624] BOJ 1749 점수따먹기 Gold4

### ISSUE THREAD

**Issue by InbumS** [Hwarang2Platinum/algorithm#221]
# <a href="https://www.acmicpc.net/problem/1749" target="_blank">백준링크</a>

## Solver
- [ ] 김인엽 @wintiger98 
- [ ] 김경호 @kkho9654 
- [x] 송인범 @InbumS 
- [x] 오화랑 @Hwarang-Oh 
- [ ] 이찬민 @chanmin97 
- [ ] 조승기 @seungki-cho
- [ ] 김종호 @dino9881

오토에버 준비

**Comment by Hwarang-Oh** [comment]
**이거 부분 행렬이라고 문제에 써 있는데, 직사각형으로 이해하시면 됩니다. 수학적 정의의 부분 행렬의 의미와 다름**
