### ISSUE TITLE
[240902] BOJ 2075 N번째 큰 수 SILVER

### ISSUE THREAD

**Issue by InbumS** [Hwarang2Platinum/algorithm#257]
# <a href="https://www.acmicpc.net/problem/2075" target="_blank">백준링크</a>

## Solver
- [x] 김인엽 @wintiger98 
- [x] 김경호 @kkho9654 
- [x] 송인범 @InbumS 
- [x] 오화랑 @Hwarang-Oh 
- [ ] 김정규 @bladerunner3201 
- [x] 조승기 @seungki-cho
- [x] 김종호 @dino9881 
- [ ] 에이든 @Aiden-Jung 

오늘부터 2학기 알고리즘 스터디가 시작되었습니다.
"불가능 그것은 사실이 아니라 하나의 의견일 뿐이다" 이라는 말이 있습니다.
모두 위와 같이 꾸준히 문제를 풀며 각자 취업 전까지 최대한의 알고리즘 실력 상승 및 감 회복에 집중하시기 바랍니다.
모두 고맙고 감사합니다 :)

**Comment by kkho9654** [comment]
감동적인 시작 코멘트네요 ㅎㅎ~ ^^ 같이 화이팅 해보아요,,,!

**Comment by Hwarang-Oh** [comment]
저는 눈물이 흐릅니다...😂😂
