### ISSUE TITLE
[2409_2주차] BOJ 2531 회전 초밥 SILVER I

### ISSUE THREAD

**Issue by wintiger98** [Hwarang2Platinum/algorithm#276]
# <a href="https://www.acmicpc.net/problem/2531" target="_blank">백준링크</a>

## Solver
- [x] 김인엽 @wintiger98 
- [x] 김경호 @kkho9654 
- [x] 송인범 @InbumS 
- [x] 오화랑 @Hwarang-Oh 
- [ ] 김정규 @bladerunner3201 
- [ ] 조승기 @seungki-cho
- [x] 김종호 @dino9881 
- [ ] 에이든 @Aiden-Jung

**Comment by kkho9654** [comment]
아우 헷갈려 ㅋㅋ
