### ISSUE TITLE
[2410_3주차] BOJ 13905 세부 13905 G4

### ISSUE THREAD

**Issue by seungki-cho** [Hwarang2Platinum/algorithm#318]
# 아자자

# <a href="https://www.acmicpc.net/problem/13905" target="_blank">백준링크</a>

## Solver
- [x] 김인엽 @wintiger98 
- [x] 김경호 @kkho9654 
- [ ] 송인범 @InbumS 
- [x] 오화랑 @Hwarang-Oh 
- [ ] 김정규 @bladerunner3201 
- [x] 조승기 @seungki-cho
- [ ] 김종호 @dino9881 
- [ ] 에이든 @Aiden-Jung

**Comment by kkho9654** [comment]
어후 오랜만에 하니까 감도 못잡겠네요 ^^;;
