### ISSUE TITLE
[2410_3주차] BOJ 1889 수행 시간 G4

### ISSUE THREAD

**Issue by seungki-cho** [Hwarang2Platinum/algorithm#319]
# <a href="https://www.acmicpc.net/problem/16169" target="_blank">백준링크</a>
https://www.acmicpc.net/problem/16169

## Solver
- [x] 김인엽 @wintiger98 
- [ ] 김경호 @kkho9654 
- [ ] 송인범 @InbumS 
- [x] 오화랑 @Hwarang-Oh 
- [ ] 김정규 @bladerunner3201 
- [ ] 조승기 @seungki-cho
- [ ] 김종호 @dino9881 
- [ ] 에이든 @Aiden-Jung

**Comment by kkho9654** [comment]
문제가 먼가 잘못된거같은데요 선물교환인가요? 수행시간인가요?

**Comment by seungki-cho** [comment]
> 문제가 먼가 잘못된거같은데요 선물교환인가요? 수행시간인가요?
> 
> 

수정했ㅅ습니다! 수행시간입니다
