### ISSUE TITLE
[2410_4주차] BOJ 9466 텀프로젝트 골드

### ISSUE THREAD

**Issue by kkho9654** [Hwarang2Platinum/algorithm#325]
# <a href="https://www.acmicpc.net/problem/9466" target="_blank">백준링크</a>

## Solver
- [ ] 김인엽 @wintiger98 
- [ ] 김경호 @kkho9654 
- [x] 송인범 @InbumS 
- [ ] 오화랑 @Hwarang-Oh 
- [ ] 김정규 @bladerunner3201 
- [ ] 조승기 @seungki-cho
- [ ] 김종호 @dino9881 
- [ ] 에이든 @Aiden-Jung

**Comment by InbumS** [comment]
hard!..!
