### ISSUE TITLE
[20241217] BOJ 26122 가장 긴 막대 자석

### ISSUE THREAD

**Issue by Hwarang-Oh** [Hwarang2Platinum/algorithm#409]
# <a href="https://www.acmicpc.net/problem/26122" target="_blank">📝 백준링크</a>
  
  ## 📌 **Solver**  
  - [x] 김경호 @kkho9654
  - [ ] 김인엽 @wintiger98
  - [ ] 김종호 @dino9881
  - [ ] 김정규 @bladerunner3201
  - [x] 송인범 @InbumS
  - [x] 오화랑 @Hwarang-Oh
  - [ ] 이찬민 @chanmin97
  - [ ] 정현석 @Aiden-Jung
  - [ ] 조승기 @seungki-cho

  ### 📊 **Hint 1 : 난이도**  
  <details>
  <summary>난이도 보기</summary>
  Silver V
  </details>

  ### 📚 **Hint 2 : 문제 유형**

  <details>
  <summary>유형 보기</summary>
  구현, 문자열
  </details>

  ### 🧩 **Hint 3 : 풀이법 ( ChatGPT 4.0 )**  

  <details>
  <summary>풀이법 보기</summary>
  구현 예정
  </details>

**Comment by Hwarang-Oh** [comment]
과연.. 문제의 유형은 무엇일까? 출제 의도가 어떻게 되는 지 궁금하게 만드는 문제
코딩 테스트의 1번으로 나온다면 적잖게 당황할 것 같은 문제다.
이런 유형을 대비하는 것도 좋을 것 같다.
=> 본인은 분기 처리로 하긴 했지만, 복잡한 느낌이 있음

**Comment by Hwarang-Oh** [comment]
추가적으로, 문자열 함수를 잘 알고 있다면 금방 풀 수 있는 것 같기는 하다. 직접 구현하면, 시간 복잡도에서 조금은 유리하게 가져갈 수 있긴 함

**Comment by kkho9654** [comment]
문제이해부터 제대로 하기 힘드네요 휴
